### ISSUE TITLE
Programmer not responding

### ISSUE THREAD

**Issue by aldenderfer** [AtmelUniversityFrance/atmel-avr-xmini-boardmanagermodule#8]
After following your walkthrough - setting the fuse bits in Atmel Studio and programming the bootloader - I'm getting a timeout when attempting to actually program my 328pb Xplained. It's a standard "not in sync" error (resp=0x00). The board shows up in ports and reads properly (well, as a 328p, but I assume that's fine). Could this be a problem with the board defs in boards.txt?

Setup:
-- ATmega328pb Xplained, firmware v1.13
-- Atmel Studio 7.0
-- Arduino 1.6.13 (programmer: Atmel mEDBG

**Comment by aethaniel** [comment]
Hi @aldenderfer, sorry, I don't receive notifications when I'm not explicitly named in a comment :-(
Is your problem still present?

**Comment by aldenderfer** [comment]
@aethaniel No worries! I will remember this for the future.

I resolved this shortly after posting, but I can't recall how - sorry. This can be closed!
